import Script from "next/script"
import "./globals.css"

export const metadata = {
  title: "webfolio",
  description: "Generated by create next app",
  icons: {
    icon: "/assets/images/favicon.ico",
    shortcut: "/assets/images/favicon.ico", // corrected path
  },
  keywords: ["portfolio", "web developer", "React", "Next.js"],
  authors: [{ name: "Your Name", url: "https://yourwebsite.com" }],
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.googleapis.com/css?family=Poppins:100,200,300,400,500,600,700,800,900&display=swap"
          rel="stylesheet"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@200;300;400;500;600;700&display=swap"
          rel="stylesheet"
        />
        <link rel="stylesheet" href="/assets/css/plugins.css" />

        <link rel="stylesheet" href="/assets/css/style.css" />
      </head>
      <body>
        {children}

        <Script
          src="/assets/js/ScrollTrigger.min.js"
          strategy="beforeInteractive"
        />
        <Script
          src="/assets/js/ScrollSmoother.min.js"
          strategy="beforeInteractive"
        />
        <Script src="/assets/js/plugins.js" strategy="beforeInteractive" />
        <Script src="/assets/js/TweenMax.min.js" strategy="beforeInteractive" />
        <Script src="/assets/js/charming.min.js" strategy="beforeInteractive" />
        <Script src="/assets/js/countdown.js" strategy="beforeInteractive" />
        <Script src="/assets/js/gsap.min.js" strategy="beforeInteractive" />
        <Script
          src="/assets/js/splitting.min.js"
          strategy="beforeInteractive"
        />
        <Script
          src="/assets/js/isotope.pkgd.min.js"
          strategy="beforeInteractive"
        />
        <Script
          src="/assets/js/imagesloaded.pkgd.min.js"
          strategy="beforeInteractive"
        />
        <Script src="/assets/js/scripts.js" strategy="afterInteractive" />
      </body>
    </html>
  )
}
